const jCategory = [
    {
        index: 0,
        image: "../images/road-construction.jpeg",
        title: "Village Road Construction",
        rate: "₹300/day",
        av: "Skilled Work",
        companyName: "Road construction",
        location: "Village/local roads",
        workDemand: "Connectivity / Dry-season",
        dailyHours: "8 hours/day",
        description: "Jobs in rural connectivity focus on building new village roads, repairing existing ones, laying pathways, and constructing small culverts and drainage channels. These works are labor-intensive, involving tasks like digging foundations, breaking stones, leveling soil, carrying materials, and compacting earth to prepare a stable road surface. Workers under this category help in providing safe and all-weather connectivity between villages, schools, health centers, and markets. This improves not just transportation but also social and economic integration. Roads built under MGNREGS are durable community assets that support long-term development, reduce isolation of villages, and facilitate access to essential services.",
        workcategory: "Rural Road Construction (pathways, culverts, drainage)",
        workplace: "Village/local roads.",
        skillrequirement: "Mostly unskilled manual work (earth cutting, leveling, stone laying); semi-skilled for drainage and compacting.",
        implementingAgency: "Gram Panchayat under the technical guidance of Rural Engineering Department.",
        eligibilityCriteria: "Open to all adult household members, no formal education required",
    },
    {
        index: 1,
        image: "../images/village-well.jpeg",
        title: "Village Well Deepening",
        rate: "₹270/day",
        av: "Unskilled Work",
        companyName:"Water Harvesting",
        location: "Existing village wells",
        workDemand: "Summer / Water-scarce",
        dailyHours: "8 hours/day",
        description: "Village Well Deepening involves removing silt, mud, and accumulated debris from existing wells and excavating further to increase their water storage capacity. The work helps in improving groundwater recharge, ensuring year-round water availability for irrigation, drinking, and livestock needs. It is generally undertaken during summer, when wells are relatively dry and deepening is feasible. Workers are engaged in manual digging, mud removal, lifting and disposal of excavated material, and in some cases, strengthening or lining of well walls. This activity supports farmers, livestock owners, and the entire village community by reducing water scarcity and ensuring sustainable water resources.",
        workcategory: "Water Harvesting & Groundwater Recharge",
        workplace: "Existing village wells",
        skillrequirement: "Mostly unskilled manual work (earth digging, mud removal, stone lifting); semi-skilled for lining and strengthening well walls.",
        implementingAgency: "Gram Panchayat, with technical inputs from the Rural Development Department.",
        eligibilityCriteria: "Any rural adult (18+) household member willing to do manual work",
    },
    {
        index: 2,
        image: "../images/tree.jpeg",
        title: "Tree Plantation Drive",
        rate: "₹250/day",
        av: "Unskilled Work",
        companyName:"Plantation & Afforestation",
        location: "Community land, farms, roadside plantation sites",
        workDemand: "Monsoon / Green",
        dailyHours: "8 hours/day",
        description: "Plantation and afforestation jobs involve tree planting, horticulture activities, raising nurseries, and maintaining saplings. Workers are engaged in digging pits, planting trees, watering them, applying soil nutrients, and ensuring the survival of the plantation. These jobs aim at improving the local ecology, combating climate change, restoring biodiversity, and increasing green cover in rural areas. In addition, plantations provide long-term benefits like fodder for animals, fuelwood for households, and fruits for communities. Workers contribute directly to environmental sustainability, while also building assets that will serve future generations.",
        workcategory: "Plantation (tree planting, nursery raising, afforestation)",
        workplace: "Community land, farms, roadside plantation sites",
        skillrequirement: "Mostly unskilled manual work; semi-skilled for wall strengthening.",
        implementingAgency: "Gram Panchayat with technical support from Rural Development Department.",
        eligibilityCriteria: "Any rural adult (18+) with a valid Job Card willing to do manual work.",
    },
    {
        index: 3,
        image: "../images/water-flow.jpeg",
        title: "Irrigation Canal Repair",
        rate: "₹320/day",
        av: "Skilled Work",
        companyName:"Irrigation Canal Repair",
        location: "Village canals, field irrigation channels",
        workDemand: "Seasonal / Farming (especially before crop season)",
        dailyHours: "8 hours/day",
        description: "The work under water conservation and irrigation is one of the most vital activities in MGNREGS. Workers are primarily engaged in digging ponds, constructing check dams, desilting tanks, repairing canals, and creating farm bunds to ensure proper storage and distribution of water. This kind of work requires sustained physical effort, including carrying soil, breaking stones, and shaping land to hold rainwater. The purpose of such jobs is not only to provide immediate employment but also to recharge groundwater, improve irrigation facilities, and ensure year-round availability of water for agriculture. By participating in this work, laborers contribute to reducing drought risk, enhancing soil moisture, and improving agricultural productivity in their villages.",
        workcategory: "Water Conservation & Irrigation",
        workplace: "Village canals, field irrigation channels",
        skillrequirement: "Mainly unskilled digging and mud removal; semi-skilled for stone lining or embankment strengthening.",
        implementingAgency: "Gram Panchayat with technical support from the Irrigation/Rural Development Department.",
        eligibilityCriteria: "Any adult (18+) rural household member willing to do manual work",
    },
    {
        index: 4,
        image: "../images/pond-digging.jpeg",
        title: "Pond Digging & Renovation",
        rate: "₹280/day",
        av: "Unskilled Work",
        companyName:"Pond Digging & Renovation",
        location: "Village/community land or existing water bodies under Gram Panchayat",
        workDemand: "Seasonal / Pre-monsoon & Summer",
        dailyHours: "8 hours/day",
        description: "his work includes excavating new ponds and renovating existing ones through desilting, deepening, and repairing bunds. It helps in rainwater harvesting, groundwater recharge, and irrigation support for agriculture and livestock. Carried out mostly on village common land, the activity improves drinking water availability and supports fish rearing. Workers perform earthwork, mud removal, slope shaping, and bund strengthening, while semi-skilled tasks include lining or stone pitching. The work provides employment to rural households and creates a sustainable community water asset that reduces drought impact and supports long-term development.",
        workcategory: "Water Conservation & Renovation of Traditional Water Bodies",
        workplace: "Village/community land or existing water bodies under Gram Panchayat",
        skillrequirement: "Unskilled (digging, silt removal, bund repair); semi-skilled (slope shaping, lining, stone pitching).",
        implementingAgency: "Gram Panchayat with technical support from Rural Development/Water Resources Dept.",
        eligibilityCriteria: "Any rural adult (18+) with a valid Job Card willing to do manual work.",
    },
];